//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace iPower.IRMP.Flow.WinService.Poxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SecurityFactoryProviderServiceSoap", Namespace = "http://yaesoft.com/")]
    public partial class SecurityFactoryProviderService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback AppRegisterOperationCompleted;

        private System.Threading.SendOrPostCallback RolesOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllEmployeeByRoleOperationCompleted;

        /// <remarks/>
        public SecurityFactoryProviderService()
        {
            this.Url = "http://irmp.yaesoft.net/Security/SecurityFactoryProviderService.asmx";
        }

        /// <remarks/>
        public event AppRegisterCompletedEventHandler AppRegisterCompleted;

        /// <remarks/>
        public event RolesCompletedEventHandler RolesCompleted;

        /// <remarks/>
        public event GetAllEmployeeByRoleCompletedEventHandler GetAllEmployeeByRoleCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yaesoft.com/AppRegister", RequestNamespace = "http://yaesoft.com/", ResponseNamespace = "http://yaesoft.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppSystem[] AppRegister(string appName)
        {
            object[] results = this.Invoke("AppRegister", new object[] {
                    appName});
            return ((AppSystem[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAppRegister(string appName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AppRegister", new object[] {
                    appName}, callback, asyncState);
        }

        /// <remarks/>
        public AppSystem[] EndAppRegister(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AppSystem[])(results[0]));
        }

        /// <remarks/>
        public void AppRegisterAsync(string appName)
        {
            this.AppRegisterAsync(appName, null);
        }

        /// <remarks/>
        public void AppRegisterAsync(string appName, object userState)
        {
            if ((this.AppRegisterOperationCompleted == null))
            {
                this.AppRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppRegisterOperationCompleted);
            }
            this.InvokeAsync("AppRegister", new object[] {
                    appName}, this.AppRegisterOperationCompleted, userState);
        }

        private void OnAppRegisterOperationCompleted(object arg)
        {
            if ((this.AppRegisterCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppRegisterCompleted(this, new AppRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yaesoft.com/Roles", RequestNamespace = "http://yaesoft.com/", ResponseNamespace = "http://yaesoft.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SecurityRole[] Roles()
        {
            object[] results = this.Invoke("Roles", new object[0]);
            return ((SecurityRole[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRoles(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Roles", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public SecurityRole[] EndRoles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SecurityRole[])(results[0]));
        }

        /// <remarks/>
        public void RolesAsync()
        {
            this.RolesAsync(null);
        }

        /// <remarks/>
        public void RolesAsync(object userState)
        {
            if ((this.RolesOperationCompleted == null))
            {
                this.RolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRolesOperationCompleted);
            }
            this.InvokeAsync("Roles", new object[0], this.RolesOperationCompleted, userState);
        }

        private void OnRolesOperationCompleted(object arg)
        {
            if ((this.RolesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RolesCompleted(this, new RolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yaesoft.com/GetAllEmployeeByRole", RequestNamespace = "http://yaesoft.com/", ResponseNamespace = "http://yaesoft.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgEmployee[] GetAllEmployeeByRole(string roleID)
        {
            object[] results = this.Invoke("GetAllEmployeeByRole", new object[] {
                    roleID});
            return ((OrgEmployee[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllEmployeeByRole(string roleID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllEmployeeByRole", new object[] {
                    roleID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgEmployee[] EndGetAllEmployeeByRole(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgEmployee[])(results[0]));
        }

        /// <remarks/>
        public void GetAllEmployeeByRoleAsync(string roleID)
        {
            this.GetAllEmployeeByRoleAsync(roleID, null);
        }

        /// <remarks/>
        public void GetAllEmployeeByRoleAsync(string roleID, object userState)
        {
            if ((this.GetAllEmployeeByRoleOperationCompleted == null))
            {
                this.GetAllEmployeeByRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeeByRoleOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployeeByRole", new object[] {
                    roleID}, this.GetAllEmployeeByRoleOperationCompleted, userState);
        }

        private void OnGetAllEmployeeByRoleOperationCompleted(object arg)
        {
            if ((this.GetAllEmployeeByRoleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeeByRoleCompleted(this, new GetAllEmployeeByRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yaesoft.com/")]
    public partial class AppSystem
    {

        private string appIDField;

        private string appNameField;

        /// <remarks/>
        public string AppID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
            }
        }

        /// <remarks/>
        public string AppName
        {
            get
            {
                return this.appNameField;
            }
            set
            {
                this.appNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yaesoft.com/")]
    public partial class OrgEmployee
    {

        private string employeeIDField;

        private string departmentIDField;

        private string postIDField;

        private string employeeNameField;

        /// <remarks/>
        public string EmployeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }

        /// <remarks/>
        public string DepartmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }

        /// <remarks/>
        public string PostID
        {
            get
            {
                return this.postIDField;
            }
            set
            {
                this.postIDField = value;
            }
        }

        /// <remarks/>
        public string EmployeeName
        {
            get
            {
                return this.employeeNameField;
            }
            set
            {
                this.employeeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yaesoft.com/")]
    public partial class SecurityRole
    {

        private string roleIDField;

        private string roleNameField;

        private string parentRoleIDField;

        /// <remarks/>
        public string RoleID
        {
            get
            {
                return this.roleIDField;
            }
            set
            {
                this.roleIDField = value;
            }
        }

        /// <remarks/>
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }

        /// <remarks/>
        public string ParentRoleID
        {
            get
            {
                return this.parentRoleIDField;
            }
            set
            {
                this.parentRoleIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AppRegisterCompletedEventHandler(object sender, AppRegisterCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AppRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AppSystem[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AppSystem[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void RolesCompletedEventHandler(object sender, RolesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SecurityRole[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SecurityRole[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetAllEmployeeByRoleCompletedEventHandler(object sender, GetAllEmployeeByRoleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeeByRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllEmployeeByRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgEmployee[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgEmployee[])(this.results[0]));
            }
        }
    }
}