//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace iPower.IRMP.Org.Poxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "OrgFactoryServiceSoap", Namespace = "http://ipower.org/")]
    internal partial class OrgFactoryServicePoxy : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetAllDepartmentOperationCompleted;

        private System.Threading.SendOrPostCallback GetSubChargeOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllRankOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllPostOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllEmployeeOperationCompleted;

        /// <remarks/>
        public OrgFactoryServicePoxy()
        {
            this.Url = "http://irmp.yaesoft.net/Org/OrgFactoryService.asmx";
        }

        /// <remarks/>
        public event GetAllDepartmentCompletedEventHandler GetAllDepartmentCompleted;

        /// <remarks/>
        public event GetSubChargeCompletedEventHandler GetSubChargeCompleted;

        /// <remarks/>
        public event GetAllRankCompletedEventHandler GetAllRankCompleted;

        /// <remarks/>
        public event GetAllPostCompletedEventHandler GetAllPostCompleted;

        /// <remarks/>
        public event GetAllEmployeeCompletedEventHandler GetAllEmployeeCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/GetAllDepartment", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgDepartment[] GetAllDepartment(string departmentID)
        {
            object[] results = this.Invoke("GetAllDepartment", new object[] {
                    departmentID});
            return ((OrgDepartment[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllDepartment(string departmentID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllDepartment", new object[] {
                    departmentID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgDepartment[] EndGetAllDepartment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgDepartment[])(results[0]));
        }

        /// <remarks/>
        public void GetAllDepartmentAsync(string departmentID)
        {
            this.GetAllDepartmentAsync(departmentID, null);
        }

        /// <remarks/>
        public void GetAllDepartmentAsync(string departmentID, object userState)
        {
            if ((this.GetAllDepartmentOperationCompleted == null))
            {
                this.GetAllDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetAllDepartment", new object[] {
                    departmentID}, this.GetAllDepartmentOperationCompleted, userState);
        }

        private void OnGetAllDepartmentOperationCompleted(object arg)
        {
            if ((this.GetAllDepartmentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDepartmentCompleted(this, new GetAllDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/GetSubCharge", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgDepartment[] GetSubCharge(string employeeID)
        {
            object[] results = this.Invoke("GetSubCharge", new object[] {
                    employeeID});
            return ((OrgDepartment[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetSubCharge(string employeeID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetSubCharge", new object[] {
                    employeeID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgDepartment[] EndGetSubCharge(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgDepartment[])(results[0]));
        }

        /// <remarks/>
        public void GetSubChargeAsync(string employeeID)
        {
            this.GetSubChargeAsync(employeeID, null);
        }

        /// <remarks/>
        public void GetSubChargeAsync(string employeeID, object userState)
        {
            if ((this.GetSubChargeOperationCompleted == null))
            {
                this.GetSubChargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubChargeOperationCompleted);
            }
            this.InvokeAsync("GetSubCharge", new object[] {
                    employeeID}, this.GetSubChargeOperationCompleted, userState);
        }

        private void OnGetSubChargeOperationCompleted(object arg)
        {
            if ((this.GetSubChargeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubChargeCompleted(this, new GetSubChargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/GetAllRank", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgRank[] GetAllRank(string rankID)
        {
            object[] results = this.Invoke("GetAllRank", new object[] {
                    rankID});
            return ((OrgRank[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllRank(string rankID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllRank", new object[] {
                    rankID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgRank[] EndGetAllRank(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgRank[])(results[0]));
        }

        /// <remarks/>
        public void GetAllRankAsync(string rankID)
        {
            this.GetAllRankAsync(rankID, null);
        }

        /// <remarks/>
        public void GetAllRankAsync(string rankID, object userState)
        {
            if ((this.GetAllRankOperationCompleted == null))
            {
                this.GetAllRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRankOperationCompleted);
            }
            this.InvokeAsync("GetAllRank", new object[] {
                    rankID}, this.GetAllRankOperationCompleted, userState);
        }

        private void OnGetAllRankOperationCompleted(object arg)
        {
            if ((this.GetAllRankCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRankCompleted(this, new GetAllRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/GetAllPost", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgPost[] GetAllPost(string postID)
        {
            object[] results = this.Invoke("GetAllPost", new object[] {
                    postID});
            return ((OrgPost[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllPost(string postID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllPost", new object[] {
                    postID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgPost[] EndGetAllPost(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgPost[])(results[0]));
        }

        /// <remarks/>
        public void GetAllPostAsync(string postID)
        {
            this.GetAllPostAsync(postID, null);
        }

        /// <remarks/>
        public void GetAllPostAsync(string postID, object userState)
        {
            if ((this.GetAllPostOperationCompleted == null))
            {
                this.GetAllPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPostOperationCompleted);
            }
            this.InvokeAsync("GetAllPost", new object[] {
                    postID}, this.GetAllPostOperationCompleted, userState);
        }

        private void OnGetAllPostOperationCompleted(object arg)
        {
            if ((this.GetAllPostCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPostCompleted(this, new GetAllPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/GetAllEmployee", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrgEmployee[] GetAllEmployee(string employeeID)
        {
            object[] results = this.Invoke("GetAllEmployee", new object[] {
                    employeeID});
            return ((OrgEmployee[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllEmployee(string employeeID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllEmployee", new object[] {
                    employeeID}, callback, asyncState);
        }

        /// <remarks/>
        public OrgEmployee[] EndGetAllEmployee(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrgEmployee[])(results[0]));
        }

        /// <remarks/>
        public void GetAllEmployeeAsync(string employeeID)
        {
            this.GetAllEmployeeAsync(employeeID, null);
        }

        /// <remarks/>
        public void GetAllEmployeeAsync(string employeeID, object userState)
        {
            if ((this.GetAllEmployeeOperationCompleted == null))
            {
                this.GetAllEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeeOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployee", new object[] {
                    employeeID}, this.GetAllEmployeeOperationCompleted, userState);
        }

        private void OnGetAllEmployeeOperationCompleted(object arg)
        {
            if ((this.GetAllEmployeeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeeCompleted(this, new GetAllEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    internal partial class OrgDepartment
    {

        private string departmentIDField;

        private string parentDepartmentIDField;

        private string departmentNameField;

        private int orderField;

        /// <remarks/>
        public string DepartmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }

        /// <remarks/>
        public string ParentDepartmentID
        {
            get
            {
                return this.parentDepartmentIDField;
            }
            set
            {
                this.parentDepartmentIDField = value;
            }
        }

        /// <remarks/>
        public string DepartmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    internal partial class OrgEmployee
    {

        private string employeeIDField;

        private string employeSignField;

        private string employeeNameField;

        private string departmentIDField;

        private string postIDField;

        private int orderField;

        /// <remarks/>
        public string EmployeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }

        /// <remarks/>
        public string EmployeSign
        {
            get
            {
                return this.employeSignField;
            }
            set
            {
                this.employeSignField = value;
            }
        }

        /// <remarks/>
        public string EmployeeName
        {
            get
            {
                return this.employeeNameField;
            }
            set
            {
                this.employeeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostID
        {
            get
            {
                return this.postIDField;
            }
            set
            {
                this.postIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    internal partial class OrgPost
    {

        private string postIDField;

        private string parentPostIDField;

        private string postNameField;

        private string departmentIDField;

        private string rankIDField;

        /// <remarks/>
        public string PostID
        {
            get
            {
                return this.postIDField;
            }
            set
            {
                this.postIDField = value;
            }
        }

        /// <remarks/>
        public string ParentPostID
        {
            get
            {
                return this.parentPostIDField;
            }
            set
            {
                this.parentPostIDField = value;
            }
        }

        /// <remarks/>
        public string PostName
        {
            get
            {
                return this.postNameField;
            }
            set
            {
                this.postNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rankID
        {
            get
            {
                return this.rankIDField;
            }
            set
            {
                this.rankIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    internal partial class OrgRank
    {

        private string parentRankIDField;

        private string rankIDField;

        private string rankNameField;

        /// <remarks/>
        public string ParentRankID
        {
            get
            {
                return this.parentRankIDField;
            }
            set
            {
                this.parentRankIDField = value;
            }
        }

        /// <remarks/>
        public string RankID
        {
            get
            {
                return this.rankIDField;
            }
            set
            {
                this.rankIDField = value;
            }
        }

        /// <remarks/>
        public string RankName
        {
            get
            {
                return this.rankNameField;
            }
            set
            {
                this.rankNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void GetAllDepartmentCompletedEventHandler(object sender, GetAllDepartmentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class GetAllDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgDepartment[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgDepartment[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void GetSubChargeCompletedEventHandler(object sender, GetSubChargeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class GetSubChargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetSubChargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgDepartment[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgDepartment[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void GetAllRankCompletedEventHandler(object sender, GetAllRankCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class GetAllRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgRank[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgRank[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void GetAllPostCompletedEventHandler(object sender, GetAllPostCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class GetAllPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgPost[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgPost[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void GetAllEmployeeCompletedEventHandler(object sender, GetAllEmployeeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class GetAllEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrgEmployee[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrgEmployee[])(this.results[0]));
            }
        }
    }
}